version: '3.8'
services:
   namenode:
      image: apache/hadoop:3
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/opt/hadoop/dfs/name"
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
          endpoint_mode: dnsrr
          mode: global
      networks:
        - hadoop
      volumes:
        - /data:/var/lib/docker/volumes/f3d68f3bf8ec2a8cc8e11424d874946b4b6cd6a20af8c2670cf1d6032c58e1bb/_data

   datanode:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - hadoop
      volumes:
        - /data:/var/lib/docker/volumes/f3d68f3bf8ec2a8cc8e11424d874946b4b6cd6a20af8c2670cf1d6032c58e1bb/_data

   resourcemanager:
      image: apache/hadoop:3
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./test.sh:/opt/hadoop/test.sh
        - /data:/var/lib/docker/volumes/f3d68f3bf8ec2a8cc8e11424d874946b4b6cd6a20af8c2670cf1d6032c58e1bb/_data
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - hadoop

   nodemanager:
      image: apache/hadoop:3
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - hadoop
      volumes:
        - /data:/var/lib/docker/volumes/f3d68f3bf8ec2a8cc8e11424d874946b4b6cd6a20af8c2670cf1d6032c58e1bb/_data

networks:
  hadoop:
